apiVersion: v2
name: ska-ost-osd
description: A Helm chart for deploying the Observatory Static Data (OSD) on Kubernetes
type: application
version: 5.1.0
appVersion: 5.1.0
icon: https://www.skatelescope.org/wp-content/uploads/2016/07/09545_NEW_LOGO_2014.png
